#ARCH=arm
#CROSS_COMPILE=arm-linux-gnueabi-
#DRIVER = spike

#TARGET = nrf51822
#OBJS = nrf51822.o

obj-m += nrf51822.o
#nrf51822-objs = nrf51822.o

# Set this is your linux kernel checkout.
# KDIR := /lib/modules/$(shell uname -r)/build
# PWD := $(shell pwd)
#KDIR := /home/bradjc/git/bb-kernel/KERNEL
#PWD := $(shell pwd)

#default:
#		  $(MAKE) -C $(KDIR) M=$(PWD) modules

#clean:
#		  $(MAKE) -C $(KDIR) SUBDIRS=$(PWD) clean

#.PHONY: clean default
